"""The schedule card: one day-grouped list of source calendar events.

Same visual language as the Bilibili push card and the same offline rule --
every avatar is inlined as a data: URI before the page is rendered.
"""
from __future__ import annotations

import base64
import html
import mimetypes
from pathlib import Path
from zoneinfo import ZoneInfo

from len_bot.cards.theme import THEME_CSS

from .avatars import AvatarRotation

# Carried over from the reference plugin's schedule highlighting, recoloured
# only where it clashed with the shared palette.
HIGHLIGHT_PALETTES = {
    'pink': {'fill': '#fff5f8', 'outline': '#dd668d', 'time_fill': '#f5cede', 'badge': '#dd668d'},
    'red': {'fill': '#fff5f2', 'outline': '#b84d43', 'time_fill': '#f0d0ca', 'badge': '#b84d43'},
    'platinum': {'fill': '#fffdf6', 'outline': '#9f8758', 'time_fill': '#eee4cf', 'badge': '#9f8758'},
}

TEMPLATE_PATH = Path(__file__).resolve().parent / 'template.html'
BRAND_NAME = '爱驼推送 / Generated by LEN · LenBot'
WEEKDAYS = ('周一', '周二', '周三', '周四', '周五', '周六', '周日')


def load_template() -> str:
    return TEMPLATE_PATH.read_text(encoding='utf-8')


def _avatar_data_uri(path) -> str:
    """Operator-configured local avatars only; nothing here fetches a URL."""
    if not path:
        return ''
    try:
        file = Path(path)
        payload = file.read_bytes()
    except OSError:
        return ''
    if not payload:
        return ''
    kind = mimetypes.guess_type(file.name)[0] or 'image/png'
    return f'data:{kind};base64,' + base64.b64encode(payload).decode('ascii')


def _escaped(value) -> str:
    return html.escape(str(value or ''), quote=True).replace('\n', '<br>')


def card_description(description: str, title: str) -> str:
    """Omit source-link lines from the image, retaining the original observation."""
    if description == title:
        return ''
    return '\n'.join(line.strip() for line in description.splitlines()
                     if line.strip() and 'http://' not in line.lower() and 'https://' not in line.lower())


def _mark(highlight):
    """One highlighted slot: a palette name plus the label to print on it."""
    if not highlight:
        return None
    palette = HIGHLIGHT_PALETTES.get(highlight.get('palette') or 'pink')
    if palette is None:
        return None
    return {**palette, 'label': _escaped(highlight.get('label') or '重点')}


def build_schedule_context(schedule, title: str, *, avatar_paths=None, rotation=None,
                           highlights=None, brand_name: str = BRAND_NAME) -> dict:
    """One ScheduleResult becomes the substitution dict template.html wants."""
    zone = ZoneInfo(schedule.timezone)
    avatars = avatar_paths or {}
    cancelled = sum(1 for event in schedule.events if event.cancelled)

    marks = highlights or {}
    grouped: dict[str, list] = {}
    for event in sorted(schedule.events, key=lambda item: item.start_at):
        moment = event.start_at.astimezone(zone)
        key = f'{moment:%m月%d日} {WEEKDAYS[moment.weekday()]}'
        until = ''
        if event.end_at is not None:
            ending = event.end_at.astimezone(zone)
            until = f'至 {ending:%H:%M}' if ending.date() == moment.date() else f'至 {ending:%m/%d %H:%M}'
        description = card_description(event.description, event.title)
        grouped.setdefault(key, []).append({
            'start': '全天' if event.all_day else f'{moment:%H:%M}',
            'date': f'{moment:%m/%d}',
            'until': until,
            'host': '已取消' if event.cancelled else (event.host_signature or '源日程'),
            'avatar': (rotation.pick(event.host_signature or '') if rotation is not None else '')
                      or _avatar_data_uri(avatars.get(event.host_signature or '')),
            'title': _escaped(event.title),
            'description': _escaped(description),
            'mark': _mark(marks.get(event.source_uid)),
            'cancelled': bool(event.cancelled),
        })

    note = f'{len(schedule.events)} 条源日程'
    if cancelled:
        note += ' · 已取消事项保留标注'
    return {
        'kicker': 'A-SOUL LIVE',
        'title': title,
        'subtitle': note,
        'days': [{'label': label, 'events': events} for label, events in grouped.items()],
        'empty_text': '该范围内日历没有收录任何日程。',
        'brand_name': brand_name,
        'theme_css': THEME_CSS,
    }


async def render_schedule(schedule, title: str, renderer, *, avatar_paths=None,
                          rotation=None, highlights=None) -> bytes:
    context = build_schedule_context(schedule, title, avatar_paths=avatar_paths,
                                     rotation=rotation, highlights=highlights)
    return await renderer.render_template(load_template(), context)
