"""Deterministic local schedule cards, adapted from the upstream Pillow layout.

The warm panel, time capsule and text measurement layout derive from
astrbot_plugin_asoul/asoul_render.py. There is one configured font and no
alternate renderer, random asset selection or text fallback. See SOURCE.md.
"""
from __future__ import annotations

import io
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from PIL import Image, ImageDraw, ImageFont, ImageOps

from .calendar import CalendarEvent, ScheduleResult
from .config import CalendarConfig


def wrap_lines(draw: ImageDraw.ImageDraw, text: str, font, width: int) -> list[str]:
    lines = []
    for paragraph in text.splitlines() or [""]:
        current = ""
        for character in paragraph:
            candidate = current + character
            if current and draw.textlength(candidate, font=font) > width:
                lines.append(current)
                current = character
            else:
                current = candidate
        lines.append(current)
    return lines


class ScheduleRenderer:
    def __init__(self, config: CalendarConfig, *, resource_directory: Path):
        self.config = config
        self.resource_directory = resource_directory

    def render(self, schedule: ScheduleResult, title: str) -> bytes:
        width = self.config.image_width
        scale = width / 1080
        unit = lambda pixels: round(pixels * scale)
        font_path = self.resource_directory / self.config.font_path
        fonts = {key: ImageFont.truetype(str(font_path), unit(size)) for key, size in
                 (("title", 48), ("day", 31), ("body", 29), ("time", 30), ("meta", 21), ("footer", 19))}
        zone = ZoneInfo(schedule.timezone)
        outer, inner, gap = unit(28), unit(55), unit(16)
        time_width = unit(152)
        avatar_width = unit(120)
        measure = ImageDraw.Draw(Image.new("RGB", (width, 1)))
        start = schedule.start_at.astimezone(zone)
        end = schedule.end_at.astimezone(zone)
        days = []
        day = start.date()
        while day < end.date() or day == end.date() and end.time().isoformat() != "00:00:00":
            events = [event for event in schedule.events if self._on_day(event, day, zone)]
            days.append((day, events))
            day += timedelta(days=1)

        rows = []
        height = unit(260)
        for day, events in days:
            rows.append(("day", day, unit(74), None))
            height += unit(74) + gap
            if not events:
                rows.append(("empty", "源日历未收录本日直播安排", unit(90), None))
                height += unit(90) + gap
            for event in events:
                avatar = self.config.avatar_paths.get(event.host_signature or "")
                text_width = width - inner * 2 - time_width - unit(80) - (avatar_width if avatar else 0)
                text = event.title
                if event.description and event.description != event.title:
                    text += "\n" + event.description
                body = wrap_lines(measure, text, fonts["body"], text_width)
                line_height = unit(40)
                row_height = max(unit(180), unit(92) + len(body) * line_height)
                rows.append(("event", event, row_height, (body, avatar)))
                height += row_height + gap
        footer = [
            f"范围 [{start:%Y-%m-%d %H:%M}, {end:%Y-%m-%d %H:%M}) · {schedule.timezone}",
            f"取得 {datetime.fromtimestamp(schedule.fetched_at, zone):%Y-%m-%d %H:%M:%S} · {schedule.source_url}",
            schedule.limitation,
            "爱驼推送 / Generated by LEN · LenBot",
        ]
        footer_lines = [line for paragraph in footer
                        for line in wrap_lines(measure, paragraph, fonts["footer"], width - inner * 2)]
        height += len(footer_lines) * unit(28) + unit(50)
        image = Image.new("RGB", (width, height), "#f3ebdf")
        draw = ImageDraw.Draw(image)
        draw.ellipse((unit(-120), unit(-80), unit(420), unit(300)), fill="#efd4c2")
        draw.ellipse((width - unit(320), unit(-40), width + unit(80), unit(280)), fill="#dce8df")
        draw.rounded_rectangle((outer, outer, width - outer, height - outer), radius=unit(32), fill="#fffaf4")
        draw.rounded_rectangle((outer, outer, width - outer, unit(238)), radius=unit(32), fill="#eee0cf")
        draw.text((inner, unit(62)), "A-SOUL LIVE", font=fonts["meta"], fill="#c56d49")
        draw.text((inner, unit(110)), title, font=fonts["title"], fill="#201a17")
        draw.text((inner, unit(180)), f"{len(schedule.events)} 条源日程 · 已取消事项保留标注", font=fonts["meta"], fill="#74685f")
        top = unit(260)
        for kind, item, row_height, details in rows:
            if kind == "day":
                weekday = ("周一", "周二", "周三", "周四", "周五", "周六", "周日")[item.weekday()]
                draw.text((inner, top + unit(14)), f"{item:%m月%d日} {weekday}", font=fonts["day"], fill="#201a17")
            elif kind == "empty":
                draw.text((inner + unit(22), top + unit(20)), item, font=fonts["meta"], fill="#74685f")
            else:
                body, avatar = details
                draw.rounded_rectangle((inner, top, width - inner, top + row_height), radius=unit(26),
                    fill="#fffaf4", outline="#eadbc9", width=unit(2))
                draw.rounded_rectangle((inner + unit(18), top + unit(18), inner + time_width, top + row_height - unit(18)),
                    radius=unit(24), fill="#f1e4d3")
                moment = item.start_at.astimezone(zone)
                time_text = "全天" if item.all_day else f"{moment:%H:%M}"
                draw.text((inner + unit(32), top + unit(38)), time_text, font=fonts["time"], fill="#201a17")
                draw.text((inner + unit(32), top + unit(82)), f"{moment:%m/%d}", font=fonts["footer"], fill="#74685f")
                if item.end_at is None:
                    end_lines = ["未提供结束"]
                else:
                    ending = item.end_at.astimezone(zone)
                    end_lines = [f"至 {ending:%H:%M}"] if ending.date() == moment.date() else [f"至 {ending:%m/%d}", f"{ending:%H:%M}"]
                for index, line in enumerate(end_lines):
                    draw.text((inner + unit(22), top + unit(111) + index * unit(24)), line,
                        font=fonts["footer"], fill="#74685f")
                left = inner + time_width + unit(36)
                label = "已取消" if item.cancelled else item.host_signature or "源日程"
                draw.text((left, top + unit(23)), label, font=fonts["meta"], fill="#b84d43" if item.cancelled else "#74685f")
                for index, line in enumerate(body):
                    draw.text((left, top + unit(67) + index * unit(40)), line, font=fonts["body"], fill="#201a17")
                if avatar:
                    with Image.open(self.resource_directory / avatar) as source:
                        picture = ImageOps.exif_transpose(source).convert("RGBA")
                        picture.thumbnail((avatar_width, row_height - unit(36)), Image.Resampling.LANCZOS)
                        image.paste(picture, (width - inner - avatar_width - unit(14), top + unit(18)), picture)
            top += row_height + gap
        for line in footer_lines:
            draw.text((inner, top + unit(12)), line, font=fonts["footer"], fill="#8c8178")
            top += unit(28)
        output = io.BytesIO()
        image.save(output, format="PNG")
        return output.getvalue()

    @staticmethod
    def _on_day(event: CalendarEvent, day, zone: ZoneInfo) -> bool:
        start = datetime.combine(day, datetime.min.time(), zone)
        end = start + timedelta(days=1)
        if event.end_at is None:
            return start <= event.start_at < end
        return event.start_at < end and event.end_at > start
